---
addr: :8082
endpoints:
  kube_state_metrics:
    path: /kube-state-metrics
    target: https://localhost:8077/metrics
    refresh_interval: 5s
    insecure_skip_verify: true
    auth:
      type: Bearer
      token: foobar
  kubelet:
    path: /kubelet
    target: http://localhost:8076/metrics
    refresh_interval: 7s
